<?php

namespace ContainerRw48MSs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMutationFieldResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Overblog\GraphQLBundle\GraphQL\Relay\Mutation\MutationFieldResolver' shared autowired service.
     *
     * @return \Overblog\GraphQLBundle\GraphQL\Relay\Mutation\MutationFieldResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/ResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/AliasedInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/GraphQL/Relay/Mutation/MutationFieldResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Executor/Promise/PromiseAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/ArgumentFactory.php';

        return $container->services['Overblog\\GraphQLBundle\\GraphQL\\Relay\\Mutation\\MutationFieldResolver'] = new \Overblog\GraphQLBundle\GraphQL\Relay\Mutation\MutationFieldResolver(($container->privates['GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter'] ?? ($container->privates['GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter'] = new \GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter())), ($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] ?? ($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] = new \Overblog\GraphQLBundle\Definition\ArgumentFactory('Overblog\\GraphQLBundle\\Definition\\Argument'))));
    }
}
