<?php

namespace ContainerRw48MSs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortnnerUrlResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\GraphQL\Resolver\ShortnnerUrlResolver' shared autowired service.
     *
     * @return \App\GraphQL\Resolver\ShortnnerUrlResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/ResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/AliasedInterface.php';
        include_once \dirname(__DIR__, 4).'/src/GraphQL/Resolver/ShortnnerUrlResolver.php';

        return $container->services['App\\GraphQL\\Resolver\\ShortnnerUrlResolver'] = new \App\GraphQL\Resolver\ShortnnerUrlResolver();
    }
}
