<?php

namespace ContainerRw48MSs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeDecoratorListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Overblog\GraphQLBundle\EventListener\TypeDecoratorListener' shared service.
     *
     * @return \Overblog\GraphQLBundle\EventListener\TypeDecoratorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/EventListener/TypeDecoratorListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/ArgumentFactory.php';

        return $container->privates['Overblog\\GraphQLBundle\\EventListener\\TypeDecoratorListener'] = new \Overblog\GraphQLBundle\EventListener\TypeDecoratorListener(($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] ?? ($container->privates['Overblog\\GraphQLBundle\\Definition\\ArgumentFactory'] = new \Overblog\GraphQLBundle\Definition\ArgumentFactory('Overblog\\GraphQLBundle\\Definition\\Argument'))));
    }
}
