Query:
  type: object
  config:
    description: "Main Query"
    fields:
      shortnerUrl:
        type: ShortnerUrl
        args:
          url:
            description: "short a new url"
            type: String
        resolve: "@=resolver('ShortnerUrl', [args])"