<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ3lLixd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ3lLixd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ3lLixd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ3lLixd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ3lLixd\App_KernelDevDebugContainer([
    'container.build_hash' => 'J3lLixd',
    'container.build_id' => '97b203b7',
    'container.build_time' => 1617576799,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ3lLixd');
