<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerISxEAoO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerISxEAoO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerISxEAoO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerISxEAoO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerISxEAoO\App_KernelDevDebugContainer([
    'container.build_hash' => 'ISxEAoO',
    'container.build_id' => '63228055',
    'container.build_time' => 1617844135,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerISxEAoO');
