<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEZhrClF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEZhrClF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEZhrClF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEZhrClF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEZhrClF\App_KernelDevDebugContainer([
    'container.build_hash' => 'EZhrClF',
    'container.build_id' => 'db855cb7',
    'container.build_time' => 1617570143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEZhrClF');
