<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'overblog_graphql_endpoint' => [[], ['_controller' => 'Overblog\\GraphQLBundle\\Controller\\GraphController::endpointAction', '_format' => 'json'], [], [['text', '/graphql/']], [], []],
    'overblog_graphql_batch_endpoint' => [[], ['_controller' => 'Overblog\\GraphQLBundle\\Controller\\GraphController::batchEndpointAction', '_format' => 'json'], [], [['text', '/graphql/batch']], [], []],
    'overblog_graphql_multiple_endpoint' => [['schemaName'], ['_controller' => 'Overblog\\GraphQLBundle\\Controller\\GraphController::endpointAction', '_format' => 'json'], ['schemaName' => '[^/]+'], [['variable', '/', '[^/]+', 'schemaName', true], ['text', '/graphql/graphql']], [], []],
    'overblog_graphql_batch_multiple_endpoint' => [['schemaName'], ['_controller' => 'Overblog\\GraphQLBundle\\Controller\\GraphController::batchEndpointAction', '_format' => 'json'], ['schemaName' => '[^/]+'], [['text', '/batch'], ['variable', '/', '[^/]+', 'schemaName', true], ['text', '/graphql/graphql']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'overblog_graphiql_endpoint' => [[], ['_controller' => 'Overblog\\GraphiQLBundle\\Controller\\GraphiQLController::indexAction'], [], [['text', '/graphiql']], [], []],
    'overblog_graphiql_endpoint_multiple' => [['schemaName'], ['_controller' => 'Overblog\\GraphiQLBundle\\Controller\\GraphiQLController::indexAction'], [], [['variable', '/', '[^/]++', 'schemaName', true], ['text', '/graphiql']], [], []],
    'shortner_url' => [['path'], ['_controller' => 'App\\Controller\\ShortnerController::redirectToUrl'], [], [['variable', '/', '[^/]++', 'path', true]], [], []],
];
