<?php

namespace ContainerISxEAoO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortnerUrlCreateMutationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\GraphQL\Mutation\ShortnerUrlCreateMutation' shared autowired service.
     *
     * @return \App\GraphQL\Mutation\ShortnerUrlCreateMutation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/MutationInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/AliasedInterface.php';
        include_once \dirname(__DIR__, 4).'/src/GraphQL/Mutation/ShortnerUrlCreateMutation.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/ShortnerUrlGenerator.php';

        return $container->services['App\\GraphQL\\Mutation\\ShortnerUrlCreateMutation'] = new \App\GraphQL\Mutation\ShortnerUrlCreateMutation(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), new \App\Domain\ShortnerUrlGenerator(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)))));
    }
}
