<?php

namespace ContainerISxEAoO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortnerUrlResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\GraphQL\Resolver\ShortnerUrlResolver' shared autowired service.
     *
     * @return \App\GraphQL\Resolver\ShortnerUrlResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/ResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Definition/Resolver/AliasedInterface.php';
        include_once \dirname(__DIR__, 4).'/src/GraphQL/Resolver/ShortnerUrlResolver.php';

        return $container->services['App\\GraphQL\\Resolver\\ShortnerUrlResolver'] = new \App\GraphQL\Resolver\ShortnerUrlResolver(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
