<?php

namespace ContainerLUnJdlb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOverblogGraphql_MutationResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'overblog_graphql.mutation_resolver' shared service.
     *
     * @return \Overblog\GraphQLBundle\Resolver\MutationResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Resolver/FluentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Resolver/AbstractResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Resolver/AbstractProxyResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Resolver/MutationResolver.php';

        $container->services['overblog_graphql.mutation_resolver'] = $instance = new \Overblog\GraphQLBundle\Resolver\MutationResolver();

        $instance->addSolution('App\\GraphQL\\Mutation\\ShortnerUrlCreateMutation', [0 => [0 => $container, 1 => 'get'], 1 => [0 => 'App\\GraphQL\\Mutation\\ShortnerUrlCreateMutation']], [], ['id' => 'App\\GraphQL\\Mutation\\ShortnerUrlCreateMutation', 'aliases' => [], 'method' => '__invoke']);
        $instance->addSolution('App\\GraphQL\\Mutation\\ShortnerUrlCreateMutation::createShortner', [0 => [0 => $container, 1 => 'get'], 1 => [0 => 'App\\GraphQL\\Mutation\\ShortnerUrlCreateMutation']], [0 => 'create_shortner'], ['id' => 'App\\GraphQL\\Mutation\\ShortnerUrlCreateMutation', 'aliases' => [0 => 'create_shortner'], 'method' => 'createShortner']);

        return $instance;
    }
}
