<?php

namespace ContainerJ3lLixd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class App_KernelDevDebugContainer extends Container
{
    protected $containerDir;
    protected $targetDir;
    protected $parameters = [];
    private $buildParameters;
    protected $getService;

    public function __construct(array $buildParameters = [], $containerDir = __DIR__)
    {
        $this->getService = \Closure::fromCallable([$this, 'getService']);
        $this->buildParameters = $buildParameters;
        $this->containerDir = $containerDir;
        $this->targetDir = \dirname($containerDir);
        $this->parameters = $this->getDefaultParameters();

        $this->services = $this->privates = [];
        $this->syntheticIds = [
            'kernel' => true,
        ];
        $this->methodMap = [
            'event_dispatcher' => 'getEventDispatcherService',
            'http_kernel' => 'getHttpKernelService',
            'overblog_graphql.cache_compiler' => 'getOverblogGraphql_CacheCompilerService',
            'overblog_graphql.event_listener.classloader_listener' => 'getOverblogGraphql_EventListener_ClassloaderListenerService',
            'request_stack' => 'getRequestStackService',
            'router' => 'getRouterService',
            'cache_clearer' => 'getCacheClearerService',
            'filesystem' => 'getFilesystemService',
            'twig' => 'getTwigService',
        ];
        $this->fileMap = [
            '.container.private.cache_clearer' => 'get_Container_Private_CacheClearerService',
            '.container.private.filesystem' => 'get_Container_Private_FilesystemService',
            '.container.private.twig' => 'get_Container_Private_TwigService',
            'App\\GraphQL\\Resolver\\ShortnnerUrlResolver' => 'getShortnnerUrlResolverService',
            'Overblog\\GraphQLBundle\\Command\\CompileCommand' => 'getCompileCommandService',
            'Overblog\\GraphQLBundle\\Command\\DebugCommand' => 'getDebugCommandService',
            'Overblog\\GraphQLBundle\\Command\\GraphQLDumpSchemaCommand' => 'getGraphQLDumpSchemaCommandService',
            'Overblog\\GraphQLBundle\\Command\\ValidateCommand' => 'getValidateCommandService',
            'Overblog\\GraphQLBundle\\Controller\\GraphController' => 'getGraphControllerService',
            'Overblog\\GraphQLBundle\\EventListener\\ErrorLoggerListener' => 'getErrorLoggerListenerService',
            'Overblog\\GraphQLBundle\\GraphQL\\Relay\\Mutation\\MutationFieldResolver' => 'getMutationFieldResolverService',
            'Overblog\\GraphQLBundle\\GraphQL\\Relay\\Node\\GlobalIdFieldResolver' => 'getGlobalIdFieldResolverService',
            'Overblog\\GraphQLBundle\\GraphQL\\Relay\\Node\\NodeFieldResolver' => 'getNodeFieldResolverService',
            'Overblog\\GraphQLBundle\\GraphQL\\Relay\\Node\\PluralIdentifyingRootFieldResolver' => 'getPluralIdentifyingRootFieldResolverService',
            'Overblog\\GraphQLBundle\\__DEFINITIONS__\\PageInfoType' => 'getPageInfoTypeService',
            'Overblog\\GraphQLBundle\\__DEFINITIONS__\\QueryType' => 'getQueryTypeService',
            'Overblog\\GraphQLBundle\\__DEFINITIONS__\\ShortnnerUrlType' => 'getShortnnerUrlTypeService',
            'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController' => 'getRedirectControllerService',
            'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController' => 'getTemplateControllerService',
            'cache.app' => 'getCache_AppService',
            'cache.app_clearer' => 'getCache_AppClearerService',
            'cache.global_clearer' => 'getCache_GlobalClearerService',
            'cache.system' => 'getCache_SystemService',
            'cache.system_clearer' => 'getCache_SystemClearerService',
            'cache_warmer' => 'getCacheWarmerService',
            'console.command_loader' => 'getConsole_CommandLoaderService',
            'container.env_var_processors_locator' => 'getContainer_EnvVarProcessorsLocatorService',
            'error_controller' => 'getErrorControllerService',
            'overblog_graphiql.controller' => 'getOverblogGraphiql_ControllerService',
            'overblog_graphql.access_resolver' => 'getOverblogGraphql_AccessResolverService',
            'overblog_graphql.arguments_transformer' => 'getOverblogGraphql_ArgumentsTransformerService',
            'overblog_graphql.definition.boolean_type' => 'getOverblogGraphql_Definition_BooleanTypeService',
            'overblog_graphql.definition.float_type' => 'getOverblogGraphql_Definition_FloatTypeService',
            'overblog_graphql.definition.id_type' => 'getOverblogGraphql_Definition_IdTypeService',
            'overblog_graphql.definition.int_type' => 'getOverblogGraphql_Definition_IntTypeService',
            'overblog_graphql.definition.string_type' => 'getOverblogGraphql_Definition_StringTypeService',
            'overblog_graphql.mutation_resolver' => 'getOverblogGraphql_MutationResolverService',
            'overblog_graphql.react.promise_adapter' => 'getOverblogGraphql_React_PromiseAdapterService',
            'overblog_graphql.request_batch_parser' => 'getOverblogGraphql_RequestBatchParserService',
            'overblog_graphql.request_executor' => 'getOverblogGraphql_RequestExecutorService',
            'overblog_graphql.request_parser' => 'getOverblogGraphql_RequestParserService',
            'overblog_graphql.resolver_resolver' => 'getOverblogGraphql_ResolverResolverService',
            'overblog_graphql.type_resolver' => 'getOverblogGraphql_TypeResolverService',
            'routing.loader' => 'getRouting_LoaderService',
            'services_resetter' => 'getServicesResetterService',
            'session' => 'getSessionService',
        ];
        $this->aliases = [
            'Overblog\\GraphiQLBundle\\Controller\\GraphiQLController' => 'overblog_graphiql.controller',
        ];

        $this->privates['service_container'] = function () {
            include_once \dirname(__DIR__, 4).'/vendor/symfony/event-dispatcher/EventSubscriberInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/ResponseListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/StreamedResponseListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/LocaleListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/ValidateRequestListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/DisallowRobotsIndexingListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/ErrorListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/psr/event-dispatcher/src/EventDispatcherInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/event-dispatcher-contracts/EventDispatcherInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/event-dispatcher/EventDispatcherInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/event-dispatcher/EventDispatcher.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/HttpKernelInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/TerminableInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/HttpKernel.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ControllerResolverInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ControllerResolver.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerResolver.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolverInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/ControllerMetadata/ArgumentMetadataFactoryInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/ControllerMetadata/ArgumentMetadataFactory.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestStack.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/LocaleAwareListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/AbstractSessionListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/SessionListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/psr/container/src/ContainerInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceProviderInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceLocatorTrait.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ServiceLocator.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Debug/FileLinkFormatter.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/RequestContext.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/expression-language/ExpressionFunctionProviderInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Matcher/ExpressionLanguageProvider.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/RouterListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/EventListener/ClassLoaderListener.php';
            include_once \dirname(__DIR__, 4).'/vendor/psr/log/Psr/Log/LoggerInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/psr/log/Psr/Log/AbstractLogger.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Log/Logger.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/RequestContextAwareInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Matcher/UrlMatcherInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Generator/UrlGeneratorInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/RouterInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Matcher/RequestMatcherInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Router.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheWarmer/WarmableInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceSubscriberInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Routing/Router.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ParameterBag/ParameterBagInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ParameterBag/FrozenParameterBag.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ParameterBag/ContainerBagInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ParameterBag/ContainerBag.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/config/ConfigCacheFactoryInterface.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/config/ResourceCheckerConfigCacheFactory.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/lib/generator/src/Generator/AbstractClassGenerator.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/lib/generator/src/Generator/AbstractTypeGenerator.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/lib/generator/src/Generator/TypeGenerator.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Generator/TypeGenerator.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/expression-language/ExpressionLanguage.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionLanguage.php';
            include_once \dirname(__DIR__, 4).'/vendor/symfony/expression-language/ExpressionFunction.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Call.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/DependencyInjection/Parameter.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/DependencyInjection/Service.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Arguments.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/IsTypeOf.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Mutation.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/FromGlobalID.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/GlobalID.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/IdFetcherCallback.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/MutateAndGetPayloadCallback.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/ResolveSingleInputCallback.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/GraphQL/Resolver.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/NewObject.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/GetUser.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/HasAnyPermission.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/HasAnyRole.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/HasPermission.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/HasRole.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/IsAnonymous.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/IsAuthenticated.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/IsFullyAuthenticated.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/IsGranted.php';
            include_once \dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/ExpressionLanguage/ExpressionFunction/Security/IsRememberMe.php';
        };
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return require $this->containerDir.\DIRECTORY_SEPARATOR.'removed-ids.php';
    }

    protected function load($file, $lazyLoad = true)
    {
        if (class_exists($class = __NAMESPACE__.'\\'.$file, false)) {
            return $class::do($this, $lazyLoad);
        }

        if ('.' === $file[-4]) {
            $class = substr($class, 0, -4);
        } else {
            $file .= '.php';
        }

        $service = require $this->containerDir.\DIRECTORY_SEPARATOR.$file;

        return class_exists($class, false) ? $class::do($this, $lazyLoad) : $service;
    }

    /**
     * Gets the public 'event_dispatcher' shared service.
     *
     * @return \Symfony\Component\EventDispatcher\EventDispatcher
     */
    protected function getEventDispatcherService()
    {
        $this->services['event_dispatcher'] = $instance = new \Symfony\Component\EventDispatcher\EventDispatcher();

        $instance->addListener('graphql.error_formatting', [0 => function () {
            return ($this->privates['Overblog\\GraphQLBundle\\Validator\\Formatter'] ?? ($this->privates['Overblog\\GraphQLBundle\\Validator\\Formatter'] = new \Overblog\GraphQLBundle\Validator\Formatter()));
        }, 1 => 'onErrorFormatting'], 0);
        $instance->addListener('graphql.executor.context', [0 => function () {
            return ($this->privates['Overblog\\GraphQLBundle\\EventListener\\RequestFilesListener'] ?? $this->load('getRequestFilesListenerService'));
        }, 1 => 'onExecutorContextEvent'], 0);
        $instance->addListener('graphql.type_loaded', [0 => function () {
            return ($this->privates['Overblog\\GraphQLBundle\\EventListener\\TypeDecoratorListener'] ?? $this->load('getTypeDecoratorListenerService'));
        }, 1 => 'onTypeLoaded'], 0);
        $instance->addListener('graphql.error_formatting', [0 => function () {
            return ($this->privates['Overblog\\GraphQLBundle\\EventListener\\ValidationErrorsListener'] ?? ($this->privates['Overblog\\GraphQLBundle\\EventListener\\ValidationErrorsListener'] = new \Overblog\GraphQLBundle\EventListener\ValidationErrorsListener()));
        }, 1 => 'onErrorFormatting'], 0);
        $instance->addListener('graphql.post_executor', [0 => function () {
            return ($this->privates['Overblog\\GraphQLBundle\\EventListener\\ErrorHandlerListener'] ?? $this->load('getErrorHandlerListenerService'));
        }, 1 => 'onPostExecutor'], 0);
        $instance->addListener('graphql.error_formatting', [0 => function () {
            return ($this->services['Overblog\\GraphQLBundle\\EventListener\\ErrorLoggerListener'] ?? $this->load('getErrorLoggerListenerService'));
        }, 1 => 'onErrorFormatting'], 0);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->services['overblog_graphql.event_listener.classloader_listener'] ?? $this->getOverblogGraphql_EventListener_ClassloaderListenerService());
        }, 1 => 'load'], 255);
        $instance->addListener('console.command', [0 => function () {
            return ($this->services['overblog_graphql.event_listener.classloader_listener'] ?? $this->getOverblogGraphql_EventListener_ClassloaderListenerService());
        }, 1 => 'load'], 255);
        $instance->addListener('kernel.response', [0 => function () {
            return ($this->privates['response_listener'] ?? ($this->privates['response_listener'] = new \Symfony\Component\HttpKernel\EventListener\ResponseListener('UTF-8')));
        }, 1 => 'onKernelResponse'], 0);
        $instance->addListener('kernel.response', [0 => function () {
            return ($this->privates['streamed_response_listener'] ?? ($this->privates['streamed_response_listener'] = new \Symfony\Component\HttpKernel\EventListener\StreamedResponseListener()));
        }, 1 => 'onKernelResponse'], -1024);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->privates['locale_listener'] ?? $this->getLocaleListenerService());
        }, 1 => 'setDefaultLocale'], 100);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->privates['locale_listener'] ?? $this->getLocaleListenerService());
        }, 1 => 'onKernelRequest'], 16);
        $instance->addListener('kernel.finish_request', [0 => function () {
            return ($this->privates['locale_listener'] ?? $this->getLocaleListenerService());
        }, 1 => 'onKernelFinishRequest'], 0);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->privates['validate_request_listener'] ?? ($this->privates['validate_request_listener'] = new \Symfony\Component\HttpKernel\EventListener\ValidateRequestListener()));
        }, 1 => 'onKernelRequest'], 256);
        $instance->addListener('kernel.response', [0 => function () {
            return ($this->privates['disallow_search_engine_index_response_listener'] ?? ($this->privates['disallow_search_engine_index_response_listener'] = new \Symfony\Component\HttpKernel\EventListener\DisallowRobotsIndexingListener()));
        }, 1 => 'onResponse'], -255);
        $instance->addListener('kernel.controller_arguments', [0 => function () {
            return ($this->privates['exception_listener'] ?? $this->getExceptionListenerService());
        }, 1 => 'onControllerArguments'], 0);
        $instance->addListener('kernel.exception', [0 => function () {
            return ($this->privates['exception_listener'] ?? $this->getExceptionListenerService());
        }, 1 => 'logKernelException'], 0);
        $instance->addListener('kernel.exception', [0 => function () {
            return ($this->privates['exception_listener'] ?? $this->getExceptionListenerService());
        }, 1 => 'onKernelException'], -128);
        $instance->addListener('kernel.response', [0 => function () {
            return ($this->privates['exception_listener'] ?? $this->getExceptionListenerService());
        }, 1 => 'removeCspHeader'], -128);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->privates['locale_aware_listener'] ?? $this->getLocaleAwareListenerService());
        }, 1 => 'onKernelRequest'], 15);
        $instance->addListener('kernel.finish_request', [0 => function () {
            return ($this->privates['locale_aware_listener'] ?? $this->getLocaleAwareListenerService());
        }, 1 => 'onKernelFinishRequest'], -15);
        $instance->addListener('console.error', [0 => function () {
            return ($this->privates['console.error_listener'] ?? $this->load('getConsole_ErrorListenerService'));
        }, 1 => 'onConsoleError'], -128);
        $instance->addListener('console.terminate', [0 => function () {
            return ($this->privates['console.error_listener'] ?? $this->load('getConsole_ErrorListenerService'));
        }, 1 => 'onConsoleTerminate'], -128);
        $instance->addListener('console.error', [0 => function () {
            return ($this->privates['console.suggest_missing_package_subscriber'] ?? ($this->privates['console.suggest_missing_package_subscriber'] = new \Symfony\Bundle\FrameworkBundle\EventListener\SuggestMissingPackageSubscriber()));
        }, 1 => 'onConsoleError'], 0);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->privates['session_listener'] ?? $this->getSessionListenerService());
        }, 1 => 'onKernelRequest'], 128);
        $instance->addListener('kernel.response', [0 => function () {
            return ($this->privates['session_listener'] ?? $this->getSessionListenerService());
        }, 1 => 'onKernelResponse'], -1000);
        $instance->addListener('kernel.finish_request', [0 => function () {
            return ($this->privates['session_listener'] ?? $this->getSessionListenerService());
        }, 1 => 'onFinishRequest'], 0);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->privates['debug.debug_handlers_listener'] ?? $this->getDebug_DebugHandlersListenerService());
        }, 1 => 'configure'], 2048);
        $instance->addListener('console.command', [0 => function () {
            return ($this->privates['debug.debug_handlers_listener'] ?? $this->getDebug_DebugHandlersListenerService());
        }, 1 => 'configure'], 2048);
        $instance->addListener('kernel.request', [0 => function () {
            return ($this->privates['router_listener'] ?? $this->getRouterListenerService());
        }, 1 => 'onKernelRequest'], 32);
        $instance->addListener('kernel.finish_request', [0 => function () {
            return ($this->privates['router_listener'] ?? $this->getRouterListenerService());
        }, 1 => 'onKernelFinishRequest'], 0);
        $instance->addListener('kernel.exception', [0 => function () {
            return ($this->privates['router_listener'] ?? $this->getRouterListenerService());
        }, 1 => 'onKernelException'], -64);

        return $instance;
    }

    /**
     * Gets the public 'http_kernel' shared service.
     *
     * @return \Symfony\Component\HttpKernel\HttpKernel
     */
    protected function getHttpKernelService()
    {
        return $this->services['http_kernel'] = new \Symfony\Component\HttpKernel\HttpKernel(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), new \Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver($this, ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()))), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), new \Symfony\Component\HttpKernel\Controller\ArgumentResolver(new \Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory(), new RewindableGenerator(function () {
            yield 0 => ($this->privates['argument_resolver.request_attribute'] ?? ($this->privates['argument_resolver.request_attribute'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver()));
            yield 1 => ($this->privates['argument_resolver.request'] ?? ($this->privates['argument_resolver.request'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver()));
            yield 2 => ($this->privates['argument_resolver.session'] ?? ($this->privates['argument_resolver.session'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver()));
            yield 3 => ($this->privates['argument_resolver.service'] ?? $this->load('getArgumentResolver_ServiceService'));
            yield 4 => ($this->privates['argument_resolver.default'] ?? ($this->privates['argument_resolver.default'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver()));
            yield 5 => ($this->privates['argument_resolver.variadic'] ?? ($this->privates['argument_resolver.variadic'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver()));
        }, 6)));
    }

    /**
     * Gets the public 'overblog_graphql.cache_compiler' shared service.
     *
     * @return \Overblog\GraphQLBundle\Generator\TypeGenerator
     */
    protected function getOverblogGraphql_CacheCompilerService()
    {
        $this->services['overblog_graphql.cache_compiler'] = $instance = new \Overblog\GraphQLBundle\Generator\TypeGenerator('Overblog\\GraphQLBundle\\__DEFINITIONS__', [0 => (\dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Resources/skeleton')], NULL, $this->parameters['overblog_graphql_types.config'], true, NULL, $this->targetDir.'', NULL);

        $a = new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionLanguage(NULL);
        $a->addGlobalName('globalVariable->get(\'typeResolver\')', 'typeResolver');
        $a->addGlobalName('globalVariable->get(\'argumentFactory\')', 'argumentFactory');
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Call());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\DependencyInjection\Parameter());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\DependencyInjection\Service());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Arguments());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\IsTypeOf());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Mutation());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Relay\FromGlobalID());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Relay\GlobalID());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Relay\IdFetcherCallback());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Relay\MutateAndGetPayloadCallback());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Relay\ResolveSingleInputCallback());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Resolver());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\NewObject());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\GetUser());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\HasAnyPermission());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\HasAnyRole());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\HasPermission());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\HasRole());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\IsAnonymous());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\IsAuthenticated());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\IsFullyAuthenticated());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\IsGranted());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\IsRememberMe());
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\DependencyInjection\Parameter('param'));
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\DependencyInjection\Service('serv'));
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Mutation('mut'));
        $a->addFunction(new \Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\GraphQL\Resolver('res'));

        $instance->addUseStatement('Overblog\\GraphQLBundle\\Definition\\ConfigProcessor');
        $instance->addUseStatement('Overblog\\GraphQLBundle\\Definition\\LazyConfig');
        $instance->addUseStatement('Overblog\\GraphQLBundle\\Definition\\GlobalVariables');
        $instance->addImplement('Overblog\\GraphQLBundle\\Definition\\Type\\GeneratedTypeInterface');
        $instance->setExpressionLanguage($a);

        return $instance;
    }

    /**
     * Gets the public 'overblog_graphql.event_listener.classloader_listener' shared service.
     *
     * @return \Overblog\GraphQLBundle\EventListener\ClassLoaderListener
     */
    protected function getOverblogGraphql_EventListener_ClassloaderListenerService()
    {
        return $this->services['overblog_graphql.event_listener.classloader_listener'] = new \Overblog\GraphQLBundle\EventListener\ClassLoaderListener(($this->services['overblog_graphql.cache_compiler'] ?? $this->getOverblogGraphql_CacheCompilerService()));
    }

    /**
     * Gets the public 'request_stack' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\RequestStack
     */
    protected function getRequestStackService()
    {
        return $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack();
    }

    /**
     * Gets the public 'router' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Routing\Router
     */
    protected function getRouterService()
    {
        $this->services['router'] = $instance = new \Symfony\Bundle\FrameworkBundle\Routing\Router((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
            'routing.loader' => ['services', 'routing.loader', 'getRouting_LoaderService', true],
        ], [
            'routing.loader' => 'Symfony\\Component\\Config\\Loader\\LoaderInterface',
        ]))->withContext('router.default', $this), 'kernel::loadRoutes', ['cache_dir' => $this->targetDir.'', 'debug' => true, 'generator_class' => 'Symfony\\Component\\Routing\\Generator\\CompiledUrlGenerator', 'generator_dumper_class' => 'Symfony\\Component\\Routing\\Generator\\Dumper\\CompiledUrlGeneratorDumper', 'matcher_class' => 'Symfony\\Bundle\\FrameworkBundle\\Routing\\RedirectableCompiledUrlMatcher', 'matcher_dumper_class' => 'Symfony\\Component\\Routing\\Matcher\\Dumper\\CompiledUrlMatcherDumper', 'strict_requirements' => true, 'resource_type' => 'service'], ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()), new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($this), ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())), 'en');

        $instance->setConfigCacheFactory(new \Symfony\Component\Config\ResourceCheckerConfigCacheFactory(new RewindableGenerator(function () {
            yield 0 => ($this->privates['dependency_injection.config.container_parameters_resource_checker'] ?? ($this->privates['dependency_injection.config.container_parameters_resource_checker'] = new \Symfony\Component\DependencyInjection\Config\ContainerParametersResourceChecker($this)));
            yield 1 => ($this->privates['config.resource.self_checking_resource_checker'] ?? ($this->privates['config.resource.self_checking_resource_checker'] = new \Symfony\Component\Config\Resource\SelfCheckingResourceChecker()));
        }, 2)));
        $instance->addExpressionLanguageProvider(($this->privates['router.expression_language_provider'] ?? $this->getRouter_ExpressionLanguageProviderService()));

        return $instance;
    }

    /**
     * Gets the private 'debug.debug_handlers_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\DebugHandlersListener
     */
    protected function getDebug_DebugHandlersListenerService()
    {
        return $this->privates['debug.debug_handlers_listener'] = new \Symfony\Component\HttpKernel\EventListener\DebugHandlersListener(NULL, NULL, NULL, -1, true, ($this->privates['debug.file_link_formatter'] ?? ($this->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL))), true, NULL);
    }

    /**
     * Gets the private 'exception_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\ErrorListener
     */
    protected function getExceptionListenerService()
    {
        return $this->privates['exception_listener'] = new \Symfony\Component\HttpKernel\EventListener\ErrorListener('error_controller', ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())), true);
    }

    /**
     * Gets the private 'locale_aware_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\LocaleAwareListener
     */
    protected function getLocaleAwareListenerService()
    {
        return $this->privates['locale_aware_listener'] = new \Symfony\Component\HttpKernel\EventListener\LocaleAwareListener(new RewindableGenerator(function () {
            yield 0 => ($this->privates['slugger'] ?? ($this->privates['slugger'] = new \Symfony\Component\String\Slugger\AsciiSlugger('en')));
        }, 1), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }

    /**
     * Gets the private 'locale_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\LocaleListener
     */
    protected function getLocaleListenerService()
    {
        return $this->privates['locale_listener'] = new \Symfony\Component\HttpKernel\EventListener\LocaleListener(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), 'en', ($this->services['router'] ?? $this->getRouterService()));
    }

    /**
     * Gets the private 'logger' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Log\Logger
     */
    protected function getLoggerService()
    {
        return $this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger();
    }

    /**
     * Gets the private 'router.expression_language_provider' shared service.
     *
     * @return \Symfony\Component\Routing\Matcher\ExpressionLanguageProvider
     */
    protected function getRouter_ExpressionLanguageProviderService()
    {
        return $this->privates['router.expression_language_provider'] = new \Symfony\Component\Routing\Matcher\ExpressionLanguageProvider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
            'env' => ['privates', 'container.getenv', 'getContainer_GetenvService', true],
        ], [
            'env' => 'Closure',
        ]));
    }

    /**
     * Gets the private 'router.request_context' shared service.
     *
     * @return \Symfony\Component\Routing\RequestContext
     */
    protected function getRouter_RequestContextService()
    {
        $this->privates['router.request_context'] = $instance = \Symfony\Component\Routing\RequestContext::fromUri('', 'localhost', 'http', 80, 443);

        $instance->setParameter('_functions', ($this->privates['router.expression_language_provider'] ?? $this->getRouter_ExpressionLanguageProviderService()));

        return $instance;
    }

    /**
     * Gets the private 'router_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\RouterListener
     */
    protected function getRouterListenerService()
    {
        return $this->privates['router_listener'] = new \Symfony\Component\HttpKernel\EventListener\RouterListener(($this->services['router'] ?? $this->getRouterService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()), ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())), \dirname(__DIR__, 4), true);
    }

    /**
     * Gets the private 'session_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\SessionListener
     */
    protected function getSessionListenerService()
    {
        return $this->privates['session_listener'] = new \Symfony\Component\HttpKernel\EventListener\SessionListener(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
            'initialized_session' => ['services', 'session', NULL, true],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'session' => ['services', 'session', 'getSessionService', true],
            'session_storage' => ['privates', 'session.storage.native', 'getSession_Storage_NativeService', true],
        ], [
            'initialized_session' => '?',
            'logger' => '?',
            'request_stack' => '?',
            'session' => '?',
            'session_storage' => '?',
        ]), true);
    }

    /**
     * Gets the public 'cache_clearer' alias.
     *
     * @return object The ".container.private.cache_clearer" service.
     */
    protected function getCacheClearerService()
    {
        trigger_deprecation('symfony/framework-bundle', '5.2', 'Accessing the "cache_clearer" service directly from the container is deprecated, use dependency injection instead.');

        return $this->get('.container.private.cache_clearer');
    }

    /**
     * Gets the public 'filesystem' alias.
     *
     * @return object The ".container.private.filesystem" service.
     */
    protected function getFilesystemService()
    {
        trigger_deprecation('symfony/framework-bundle', '5.2', 'Accessing the "filesystem" service directly from the container is deprecated, use dependency injection instead.');

        return $this->get('.container.private.filesystem');
    }

    /**
     * Gets the public 'twig' alias.
     *
     * @return object The ".container.private.twig" service.
     */
    protected function getTwigService()
    {
        trigger_deprecation('symfony/twig-bundle', '5.2', 'Accessing the "twig" service directly from the container is deprecated, use dependency injection instead.');

        return $this->get('.container.private.twig');
    }

    /**
     * @return array|bool|float|int|string|null
     */
    public function getParameter(string $name)
    {
        if (isset($this->buildParameters[$name])) {
            return $this->buildParameters[$name];
        }

        if (!(isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters))) {
            throw new InvalidArgumentException(sprintf('The parameter "%s" must be defined.', $name));
        }
        if (isset($this->loadedDynamicParameters[$name])) {
            return $this->loadedDynamicParameters[$name] ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
        }

        return $this->parameters[$name];
    }

    public function hasParameter(string $name): bool
    {
        if (isset($this->buildParameters[$name])) {
            return true;
        }

        return isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters);
    }

    public function setParameter(string $name, $value): void
    {
        throw new LogicException('Impossible to call set() on a frozen ParameterBag.');
    }

    public function getParameterBag(): ParameterBagInterface
    {
        if (null === $this->parameterBag) {
            $parameters = $this->parameters;
            foreach ($this->loadedDynamicParameters as $name => $loaded) {
                $parameters[$name] = $loaded ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
            }
            foreach ($this->buildParameters as $name => $value) {
                $parameters[$name] = $value;
            }
            $this->parameterBag = new FrozenParameterBag($parameters);
        }

        return $this->parameterBag;
    }

    private $loadedDynamicParameters = [
        'kernel.runtime_environment' => false,
        'kernel.build_dir' => false,
        'kernel.cache_dir' => false,
        'kernel.secret' => false,
        'session.save_path' => false,
        'debug.container.dump' => false,
    ];
    private $dynamicParameters = [];

    private function getDynamicParameter(string $name)
    {
        switch ($name) {
            case 'kernel.runtime_environment': $value = $this->getEnv('default:kernel.environment:APP_RUNTIME_ENV'); break;
            case 'kernel.build_dir': $value = $this->targetDir.''; break;
            case 'kernel.cache_dir': $value = $this->targetDir.''; break;
            case 'kernel.secret': $value = $this->getEnv('APP_SECRET'); break;
            case 'session.save_path': $value = ($this->targetDir.''.'/sessions'); break;
            case 'debug.container.dump': $value = ($this->targetDir.''.'/App_KernelDevDebugContainer.xml'); break;
            default: throw new InvalidArgumentException(sprintf('The dynamic parameter "%s" must be defined.', $name));
        }
        $this->loadedDynamicParameters[$name] = true;

        return $this->dynamicParameters[$name] = $value;
    }

    protected function getDefaultParameters(): array
    {
        return [
            'kernel.project_dir' => \dirname(__DIR__, 4),
            'kernel.environment' => 'dev',
            'kernel.debug' => true,
            'kernel.logs_dir' => (\dirname(__DIR__, 3).'/log'),
            'kernel.bundles' => [
                'FrameworkBundle' => 'Symfony\\Bundle\\FrameworkBundle\\FrameworkBundle',
                'OverblogGraphQLBundle' => 'Overblog\\GraphQLBundle\\OverblogGraphQLBundle',
                'TwigBundle' => 'Symfony\\Bundle\\TwigBundle\\TwigBundle',
                'OverblogGraphiQLBundle' => 'Overblog\\GraphiQLBundle\\OverblogGraphiQLBundle',
            ],
            'kernel.bundles_metadata' => [
                'FrameworkBundle' => [
                    'path' => (\dirname(__DIR__, 4).'/vendor/symfony/framework-bundle'),
                    'namespace' => 'Symfony\\Bundle\\FrameworkBundle',
                ],
                'OverblogGraphQLBundle' => [
                    'path' => (\dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src'),
                    'namespace' => 'Overblog\\GraphQLBundle',
                ],
                'TwigBundle' => [
                    'path' => (\dirname(__DIR__, 4).'/vendor/symfony/twig-bundle'),
                    'namespace' => 'Symfony\\Bundle\\TwigBundle',
                ],
                'OverblogGraphiQLBundle' => [
                    'path' => (\dirname(__DIR__, 4).'/vendor/overblog/graphiql-bundle'),
                    'namespace' => 'Overblog\\GraphiQLBundle',
                ],
            ],
            'kernel.charset' => 'UTF-8',
            'kernel.container_class' => 'App_KernelDevDebugContainer',
            'container.dumper.inline_class_loader' => true,
            'event_dispatcher.event_aliases' => [
                'Symfony\\Component\\Console\\Event\\ConsoleCommandEvent' => 'console.command',
                'Symfony\\Component\\Console\\Event\\ConsoleErrorEvent' => 'console.error',
                'Symfony\\Component\\Console\\Event\\ConsoleSignalEvent' => 'console.signal',
                'Symfony\\Component\\Console\\Event\\ConsoleTerminateEvent' => 'console.terminate',
                'Symfony\\Component\\HttpKernel\\Event\\ControllerArgumentsEvent' => 'kernel.controller_arguments',
                'Symfony\\Component\\HttpKernel\\Event\\ControllerEvent' => 'kernel.controller',
                'Symfony\\Component\\HttpKernel\\Event\\ResponseEvent' => 'kernel.response',
                'Symfony\\Component\\HttpKernel\\Event\\FinishRequestEvent' => 'kernel.finish_request',
                'Symfony\\Component\\HttpKernel\\Event\\RequestEvent' => 'kernel.request',
                'Symfony\\Component\\HttpKernel\\Event\\ViewEvent' => 'kernel.view',
                'Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent' => 'kernel.exception',
                'Symfony\\Component\\HttpKernel\\Event\\TerminateEvent' => 'kernel.terminate',
            ],
            'fragment.renderer.hinclude.global_template' => NULL,
            'fragment.path' => '/_fragment',
            'kernel.http_method_override' => true,
            'kernel.trusted_hosts' => [

            ],
            'kernel.default_locale' => 'en',
            'kernel.error_controller' => 'error_controller',
            'debug.file_link_format' => NULL,
            'session.metadata.storage_key' => '_sf2_meta',
            'session.storage.options' => [
                'cache_limiter' => '0',
                'cookie_secure' => 'auto',
                'cookie_httponly' => true,
                'cookie_samesite' => 'lax',
                'gc_probability' => 1,
            ],
            'session.metadata.update_threshold' => 0,
            'data_collector.templates' => [

            ],
            'debug.error_handler.throw_at' => -1,
            'router.request_context.host' => 'localhost',
            'router.request_context.scheme' => 'http',
            'router.request_context.base_url' => '',
            'router.resource' => 'kernel::loadRoutes',
            'request_listener.http_port' => 80,
            'request_listener.https_port' => 443,
            'overblog_graphql_types.config' => [
                'Query' => [
                    'type' => 'object',
                    'class_name' => 'QueryType',
                    'inherits' => [

                    ],
                    'decorator' => false,
                    'config' => [
                        'description' => 'Main Query',
                        'fields' => [
                            'shortneerUrl' => [
                                'type' => 'ShortnnerUrl',
                                'args' => [
                                    'url' => [
                                        'description' => 'short a new url',
                                        'type' => 'String',
                                    ],
                                ],
                                'resolve' => '@=resolver(\'ShortnnerUrl\', [args])',
                            ],
                        ],
                        'name' => 'Query',
                        'builders' => [

                        ],
                        'interfaces' => [

                        ],
                    ],
                ],
                'ShortnnerUrl' => [
                    'type' => 'object',
                    'class_name' => 'ShortnnerUrlType',
                    'inherits' => [

                    ],
                    'decorator' => false,
                    'config' => [
                        'description' => 'An url shortneer',
                        'fields' => [
                            'url' => [
                                'type' => 'String',
                                'description' => 'url',
                                'args' => [

                                ],
                            ],
                        ],
                        'name' => 'ShortnnerUrl',
                        'builders' => [

                        ],
                        'interfaces' => [

                        ],
                    ],
                ],
                'PageInfo' => [
                    'type' => 'object',
                    'class_name' => 'PageInfoType',
                    'inherits' => [

                    ],
                    'decorator' => false,
                    'config' => [
                        'description' => 'Information about pagination in a connection.',
                        'fields' => [
                            'hasNextPage' => [
                                'type' => 'Boolean!',
                                'description' => 'When paginating forwards, are there more items?',
                                'args' => [

                                ],
                            ],
                            'hasPreviousPage' => [
                                'type' => 'Boolean!',
                                'description' => 'When paginating backwards, are there more items?',
                                'args' => [

                                ],
                            ],
                            'startCursor' => [
                                'type' => 'String',
                                'description' => 'When paginating backwards, the cursor to continue.',
                                'args' => [

                                ],
                            ],
                            'endCursor' => [
                                'type' => 'String',
                                'description' => 'When paginating forwards, the cursor to continue.',
                                'args' => [

                                ],
                            ],
                        ],
                        'name' => 'PageInfo',
                        'builders' => [

                        ],
                        'interfaces' => [

                        ],
                    ],
                ],
            ],
            'overblog_graphql.batching_method' => 'relay',
            'overblog_graphql.query_max_depth' => 0,
            'overblog_graphql.query_max_complexity' => 0,
            'overblog_graphql.enable_introspection' => true,
            'overblog_graphql.handle_cors' => false,
            'overblog_graphql.class_namespace' => 'Overblog\\GraphQLBundle\\__DEFINITIONS__',
            'overblog_graphql.cache_dir' => NULL,
            'overblog_graphql.cache_dir_permissions' => NULL,
            'overblog_graphql.argument_class' => 'Overblog\\GraphQLBundle\\Definition\\Argument',
            'overblog_graphql.use_experimental_executor' => false,
            'overblog_graphql.use_classloader_listener' => true,
            'overblog_graphql.resources_dir' => (\dirname(__DIR__, 4).'/vendor/overblog/graphql-bundle/src/Resources'),
            'twig.form.resources' => [
                0 => 'form_div_layout.html.twig',
            ],
            'twig.default_path' => (\dirname(__DIR__, 4).'/templates'),
            'overblog_graphiql.endpoint_resolver' => 'Overblog\\GraphiQLBundle\\Config\\GraphQLEndpoint\\Helpers\\OverblogGraphQLBundleEndpointResolver',
            'overblog_graphql_types.classes_map' => [

            ],
            'console.command.ids' => [

            ],
        ];
    }

    protected function throw($message)
    {
        throw new RuntimeException($message);
    }
}
